name: Create version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: yarn install and test
      run: echo 'Create new version only for masrer push'
